#!/bin/sh
# TicketsCAD DMR bridge container entrypoint (Phase 120, 2026-07-25).
#
#   1. Renders MMDVM_Bridge.ini from environment variables (so a Docker
#      operator configures with env, not a mounted file — though mounting your
#      own ini at $DMR_MMDVM_INI still wins if you prefer that).
#   2. Starts md380-emu (the AMBE vocoder) under qemu on UDP $AMBE_EMU_PORT and
#      waits until it actually answers — a bridge without a working vocoder
#      connects fine and then passes SILENCE, which is miserable to debug.
#   3. Execs hbp_client.py as PID 1 so signals/restarts behave.
#
# Self-test mode: `docker run --rm <image> selftest` runs the vocoder
# round-trip check only (no radio, no network) and exits non-zero on failure.
set -eu

INI="${DMR_MMDVM_INI:-/etc/ticketscad/MMDVM_Bridge.ini}"
EMU_PORT="${AMBE_EMU_PORT:-2470}"
EMU_BIN=/opt/md380-emu/md380-emu

log() { echo "[entrypoint] $*"; }

# ── 1. Start the AMBE vocoder ──────────────────────────────────────────────
start_emu() {
    # Prefer the qemu-arm-static that ships INSIDE the md380-emu package — that
    # is the pairing a working bare-metal bridge runs, and the vocoder does not
    # start reliably under Debian's stock qemu-user-static build (verified
    # 2026-07-25). Fall back to the system one only if the bundled one is absent.
    if [ -x /opt/md380-emu/qemu-arm-static ]; then
        QEMU=/opt/md380-emu/qemu-arm-static
    else
        QEMU=$(command -v qemu-arm-static || echo /usr/bin/qemu-arm-static)
    fi
    log "starting md380-emu (AMBE+2 vocoder) on UDP ${EMU_PORT} via ${QEMU}"
    "$QEMU" "$EMU_BIN" -S "$EMU_PORT" &
    EMU_PID=$!
    # Probe it rather than sleeping blindly: encode one frame of silence and
    # require a reply. Up to ~15s for slow/emulated hosts.
    i=0
    while [ "$i" -lt 30 ]; do
        if python3 - "$EMU_PORT" <<'PY' >/dev/null 2>&1
import socket, sys
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM); s.settimeout(0.5)
s.sendto(b"\x00" * 320, ("127.0.0.1", int(sys.argv[1])))
d, _ = s.recvfrom(64)
sys.exit(0 if len(d) == 7 else 1)
PY
        then
            log "md380-emu is answering on UDP ${EMU_PORT}"
            return 0
        fi
        kill -0 "$EMU_PID" 2>/dev/null || { log "FATAL: md380-emu exited during startup"; exit 1; }
        i=$((i + 1)); sleep 0.5
    done
    log "FATAL: md380-emu did not answer on UDP ${EMU_PORT} after 15s"
    exit 1
}

# ── Self-test mode ─────────────────────────────────────────────────────────
if [ "${1:-}" = "selftest" ]; then
    start_emu
    log "running AMBE codec round-trip self-test"
    exec python3 -m services.dvswitch.ambe_codec
fi

# ── 2. Render MMDVM_Bridge.ini from env (unless one was mounted) ───────────
if [ -f "$INI" ]; then
    log "using existing $INI (mounted); ignoring DMR_MASTER_* env"
else
    : "${DMR_ID:?set DMR_ID to your DMR ID (radioid.net registration)}"
    : "${DMR_CALLSIGN:?set DMR_CALLSIGN to your callsign}"
    : "${DMR_MASTER_HOST:?set DMR_MASTER_HOST to your master's hostname/IP}"
    : "${DMR_MASTER_PASSWORD:?set DMR_MASTER_PASSWORD to your master passphrase}"
    mkdir -p "$(dirname "$INI")"
    log "rendering $INI for ${DMR_CALLSIGN} (${DMR_ID}) -> ${DMR_MASTER_HOST}:${DMR_MASTER_PORT:-62031}"
    cat > "$INI" <<EOF
; Generated by the TicketsCAD bridge container from environment variables.
; Read by hbp_client.py at startup — it uses [General], [Info], [DMR] and
; [DMR Network]. Mount your own file at $INI to override.
[General]
Callsign=${DMR_CALLSIGN}
Id=${DMR_ID}
Timeout=180
Duplex=0

[Info]
RXFrequency=${DMR_RX_FREQ:-435000000}
TXFrequency=${DMR_TX_FREQ:-435000000}
Power=${DMR_POWER:-1}
Latitude=${DMR_LATITUDE:-0.0}
Longitude=${DMR_LONGITUDE:-0.0}
Height=${DMR_HEIGHT:-0}
Location=${DMR_LOCATION:-TicketsCAD}
Description=${DMR_DESCRIPTION:-TicketsCAD DMR bridge}
URL=${DMR_URL:-https://github.com/openises/TicketsCAD}

[DMR]
ColorCode=${DMR_COLOR_CODE:-1}

[DMR Network]
Address=${DMR_MASTER_HOST}
Port=${DMR_MASTER_PORT:-62031}
Password=${DMR_MASTER_PASSWORD}
Local=${DMR_LOCAL_PORT:-62032}
EOF
    chmod 0600 "$INI"
fi

start_emu

# ── 3. Hand off to the bridge ──────────────────────────────────────────────
if [ -z "${DMR_BEARER_TOKEN:-}" ]; then
    log "WARNING: DMR_BEARER_TOKEN is empty — the CAD will not be able to authenticate to this bridge."
fi
log "starting hbp_client.py (HTTP control on ${DMR_HTTP_PORT:-18091})"
exec python3 /opt/ticketscad-dvswitch/services/dvswitch/hbp_client.py \
        --mmdvm-ini "$INI" \
        --log-level "${DMR_LOG_LEVEL:-INFO}" \
        "$@"
