<?php
/**
 * Schema verification — does this install's database have the columns this
 * version of the code writes to?
 *
 * WHY (Phase 125, 2026-07-26)
 * ---------------------------
 * A database can drift away from what the code needs: a table restored from an
 * older backup, a table dropped by hand during crash recovery, a migration that
 * ran before a later column was added. When it does, nothing tells you. The
 * first symptom is a save failing with a raw PDO exception —
 * "Unknown column 'nims_resource_type' in 'INSERT INTO'" — surfacing to the
 * user as an unexplained HTTP 400.
 *
 * That is not hypothetical: a beta tester lost four rounds of back-and-forth to
 * exactly this on `teams`, and the migration runner told him "0 pending" the
 * whole time, because the migration TRACKER said the script had run. The
 * tracker records whether a script executed. It cannot know whether the schema
 * it produced still exists.
 *
 * This file answers the question the tracker cannot: compare the live schema
 * against sql/schema_manifest.json (generated by tools/gen_schema_manifest.php
 * from the writers themselves) and report exactly what is missing.
 *
 * Nothing here ever throws — it is called from health checks and from
 * db_query()'s error path, where an exception would replace the diagnosis with
 * a second failure.
 */

declare(strict_types=1);

/** Where the generated manifest lives. */
function schema_verify_manifest_path(): string
{
    return __DIR__ . '/../sql/schema_manifest.json';
}

/**
 * Load the manifest. Returns [] if absent or unreadable — a missing manifest
 * means "cannot verify", never "everything is broken".
 *
 * @return array<string, array<int, string>>  table => [column, ...]
 */
function schema_verify_manifest(): array
{
    static $cache = null;
    if ($cache !== null) {
        return $cache;
    }
    $cache = [];
    $raw = @file_get_contents(schema_verify_manifest_path());
    if ($raw === false || $raw === '') {
        return $cache;
    }
    $data = json_decode($raw, true);
    if (!is_array($data) || !isset($data['tables']) || !is_array($data['tables'])) {
        return $cache;
    }
    foreach ($data['tables'] as $tbl => $cols) {
        if (is_array($cols)) {
            $cache[strtolower((string) $tbl)] = array_map('strtolower', $cols);
        }
    }
    return $cache;
}

/**
 * Tables the code references at all — including ones it only READS.
 *
 * Phase 125b. The per-column manifest only covers tables written with a literal
 * column list, so a dropped read-only table was invisible. That is precisely
 * what a beta tester hit: of the four tables he lost to crash recovery, the
 * check would have named only some of them.
 *
 * @return array<int, string>
 */
function schema_verify_required_tables(): array
{
    static $cache = null;
    if ($cache !== null) {
        return $cache;
    }
    $cache = [];
    $raw = @file_get_contents(schema_verify_manifest_path());
    if ($raw === false || $raw === '') {
        return $cache;
    }
    $data = json_decode($raw, true);
    if (is_array($data) && !empty($data['required_tables']) && is_array($data['required_tables'])) {
        $cache = array_map('strtolower', $data['required_tables']);
    }
    return $cache;
}

/**
 * Compare the live schema against the manifest.
 *
 * @return array{
 *   available: bool, ok: bool, checked_tables: int, checked_columns: int,
 *   missing_tables: array<int,string>, missing_columns: array<string, array<int,string>>,
 *   missing_column_count: int, error: ?string
 * }
 */
function schema_verify(): array
{
    $result = [
        'available'            => false,
        'ok'                   => true,
        'checked_tables'       => 0,
        'checked_columns'      => 0,
        'missing_tables'       => [],
        'missing_columns'      => [],
        'missing_column_count' => 0,
        'error'                => null,
    ];

    $manifest = schema_verify_manifest();
    if (!$manifest) {
        $result['error'] = 'schema manifest not found (sql/schema_manifest.json)';
        return $result;
    }

    $prefix = (string) ($GLOBALS['db_prefix'] ?? '');

    $live = [];
    try {
        foreach (db_fetch_all(
            "SELECT TABLE_NAME, COLUMN_NAME FROM information_schema.COLUMNS
              WHERE TABLE_SCHEMA = DATABASE()"
        ) as $r) {
            $live[strtolower($r['TABLE_NAME'])][strtolower($r['COLUMN_NAME'])] = true;
        }
    } catch (Throwable $e) {
        $result['error'] = 'could not read information_schema';
        return $result;
    }
    if (!$live) {
        $result['error'] = 'no tables visible in this database';
        return $result;
    }

    $result['available'] = true;

    foreach ($manifest as $tbl => $cols) {
        $liveName = strtolower($prefix . $tbl);
        $result['checked_tables']++;
        $result['checked_columns'] += count($cols);

        if (!isset($live[$liveName])) {
            $result['missing_tables'][] = $tbl;
            $result['ok'] = false;
            continue;
        }
        $missing = [];
        foreach ($cols as $col) {
            if (!isset($live[$liveName][$col])) {
                $missing[] = $col;
            }
        }
        if ($missing) {
            $result['missing_columns'][$tbl] = $missing;
            $result['missing_column_count'] += count($missing);
            $result['ok'] = false;
        }
    }

    // Table-existence coverage: catches a dropped table the code only reads,
    // which the per-column pass above cannot see.
    foreach (schema_verify_required_tables() as $tbl) {
        if (isset($manifest[$tbl])) {
            continue;                                  // already checked above
        }
        $result['checked_tables']++;
        if (!isset($live[strtolower($prefix . $tbl)])) {
            $result['missing_tables'][] = $tbl;
            $result['ok'] = false;
        }
    }

    $result['missing_tables'] = array_values(array_unique($result['missing_tables']));
    sort($result['missing_tables']);
    ksort($result['missing_columns']);
    return $result;
}

/**
 * One-line human summary of a schema_verify() result.
 */
function schema_verify_summary(array $v): string
{
    if (!empty($v['error'])) {
        return 'Schema could not be verified: ' . $v['error'];
    }
    if (!empty($v['ok'])) {
        return sprintf(
            'Database schema matches this version (%d tables, %d columns checked).',
            $v['checked_tables'],
            $v['checked_columns']
        );
    }
    $bits = [];
    if ($v['missing_tables']) {
        $bits[] = count($v['missing_tables']) . ' table(s) missing';
    }
    if ($v['missing_column_count']) {
        $bits[] = $v['missing_column_count'] . ' column(s) missing from '
                . count($v['missing_columns']) . ' table(s)';
    }
    return 'Database schema does not match this version: ' . implode(', ', $bits)
         . '. Saving to the affected screens will fail until this is repaired.';
}

/**
 * The repair instruction, in one place so every surface says the same thing.
 */
function schema_verify_repair_hint(): string
{
    return 'Run: php tools/check-schema.php --repair   '
         . '(re-applies the schema migrations and re-checks; it does not delete data)';
}

// ─────────────────────────────────────────────────────────────────────────
//  Runtime drift capture
//
//  Mirrors inc/db-damage.php (Phase 121). db_query() reports MySQL error 1054
//  here so a save that fails on a missing column can say WHICH column and how
//  to fix it, instead of surfacing as an opaque 400.
// ─────────────────────────────────────────────────────────────────────────

function &_schema_drift_store(): array
{
    static $store = ['seen' => false, 'columns' => []];
    return $store;
}

/**
 * Extract the column name from a 1054 message, if this is one.
 * MySQL: "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'x' in 'INSERT INTO'"
 */
function schema_drift_classify(string $message): ?string
{
    if (stripos($message, 'unknown column') === false) {
        return null;
    }
    if (preg_match("/unknown column\s+'([^']+)'/i", $message, $m)) {
        return $m[1];
    }
    return null;
}

/**
 * Record a missing-column failure. Never throws.
 */
function schema_drift_note(Throwable $e): void
{
    $col = schema_drift_classify($e->getMessage());
    if ($col === null) {
        return;
    }
    $store = &_schema_drift_store();
    $store['seen'] = true;
    if (!in_array($col, $store['columns'], true)) {
        $store['columns'][] = $col;
    }
    // Say the same thing in the log that the API body will say. Logging
    // "run --repair" for a column no migration creates is how GH TicketsCAD#14
    // sent its reporter round in a circle.
    if (schema_verify_manifest() !== [] && !schema_drift_column_is_declared($col)) {
        error_log('schema drift: column ' . $col . ' is not declared anywhere in this '
                . 'version — no migration creates it; this is a code bug, not an '
                . 'out-of-date database');
    } else {
        error_log('schema drift: missing column ' . $col . ' — ' . schema_verify_repair_hint());
    }
}

function schema_drift_seen(): bool
{
    $store = &_schema_drift_store();
    return (bool) $store['seen'];
}

/**
 * Is this column name declared anywhere in this version's schema manifest?
 *
 * The 1054 message names the column but not the table, so this asks the
 * question the manifest CAN answer: does any table in this version declare a
 * column by that name? If none does, no migration creates it, and telling the
 * operator to run `--repair` sends them in a circle (GH TicketsCAD#14 — the
 * repair tool correctly reported "Schema OK" while the export kept failing).
 */
function schema_drift_column_is_declared(string $col): bool
{
    // schema_verify_manifest() returns the table => columns map directly,
    // already lowercased — not the raw {"tables": …} document.
    $col = strtolower($col);
    foreach (schema_verify_manifest() as $cols) {
        if (in_array($col, (array) $cols, true)) {
            return true;
        }
    }
    return false;
}

/**
 * Payload describing the drift, for an API error body.
 *
 * Two different faults produce the same MySQL 1054, and they need opposite
 * advice:
 *   - a column the manifest DECLARES is missing  → the database is behind the
 *     code; re-running the migrations is the repair.
 *   - a column NOTHING declares                  → the code asked for a column
 *     this version does not have. Migrations cannot create it, and saying
 *     "your database structure is behind the code" is backwards.
 */
function schema_drift_payload(): array
{
    $store = &_schema_drift_store();
    $cols  = $store['columns'];

    // If the manifest cannot be read, every column looks undeclared and we
    // would confidently tell every operator their install is fine. Absent
    // evidence is not evidence — fall back to the migration advice, which is
    // the safe answer when we cannot tell the two faults apart.
    $undeclared = [];
    if (schema_verify_manifest() !== []) {
        foreach ($cols as $c) {
            if (!schema_drift_column_is_declared($c)) {
                $undeclared[] = $c;
            }
        }
    }

    // Any undeclared column makes the migration advice wrong, so lead with the
    // fault that repair cannot fix rather than burying it.
    if ($undeclared) {
        $isOne = count($undeclared) === 1;
        return [
            'error'      => 'schema_column_undeclared',
            'message'    => 'A query asked for '
                          . ($isOne ? 'a column' : 'columns')
                          . ' this version of TicketsCAD does not define: '
                          . implode(', ', $undeclared)
                          . '. Your data is intact and your database is not behind — '
                          . ($isOne ? 'this column is' : 'these columns are')
                          . ' not declared anywhere in this version, so re-running the '
                          . 'migrations will not create '
                          . ($isOne ? 'it' : 'them') . '. This is a bug in the code, '
                          . 'not a problem with your install — please report it.',
            'columns'    => $cols,
            'undeclared' => $undeclared,
            'repair'     => 'Nothing to repair locally. Report at '
                          . 'https://github.com/openises/TicketsCAD/issues '
                          . 'with the column name(s) above.',
            'doc'        => 'docs/TROUBLESHOOTING.md#schema-out-of-date',
        ];
    }

    return [
        'error'    => 'schema_out_of_date',
        'message'  => 'This database is missing '
                    . (count($cols) === 1 ? 'a column' : 'columns')
                    . ' this version of TicketsCAD needs: ' . implode(', ', $cols)
                    . '. Your data is intact — the database structure is behind the code.',
        'columns'  => $cols,
        'repair'   => schema_verify_repair_hint(),
        'doc'      => 'docs/TROUBLESHOOTING.md#schema-out-of-date',
    ];
}
